apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-settlement-job
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
          containers:
            - name: settlement-job
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
